# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/XML-LibXML-PrettyPrint/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires
		"Test::Warn 0.20" ,
		"Test::More 0.61" ;
	:requires 
		"Scalar::Util" ,
		"Carp" ,
		"IO::Handle" ,
		"XML::LibXML 1.62" ,
		"common::sense" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/XML/LibXML/PrettyPrint.pm" .

